fix version

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -24,6 +24,54 @@ workflows:
       - cache-push@2:
           inputs:
             - compress_archive: "true"
+  deploy-ios:
+    steps:
+      - activate-ssh-key@4:
+          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+      - git-clone@4: {}
+      - certificate-and-profile-installer@1: {}
+      - script@1:
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                set -e
+                set -x
+
+                bash $BITRISE_SOURCE_DIR/CI/latest.sh stable
+          title: Get latest version
+      - cache-pull@2: {}
+      - script-runner@0:
+          inputs:
+            - file_path: $BITRISE_SOURCE_DIR/CI/prebuild.sh
+          title: Prebuild
+      - flutter-installer@0:
+          inputs:
+            - installation_bundle_url: $FLUTTER_ARCHIVE_URL
+      - script@1:
+          inputs:
+            - content: >-
+                #!/usr/bin/env bash
+
+                # fail if any commands fails
+
+                set -e
+
+                # debug log
+
+                set -x
+
+
+                flutter build ios --config-only --no-codesign --release
+                --build-number $GIT_CLONE_COMMIT_COUNT
+          title: flutter build ios
+      - xcode-archive@3: {}
+      - deploy-to-itunesconnect-application-loader@1:
+          inputs:
+            - password: $APPLE_PASSWORD
+            - app_password: $APPLE_2FA
+            - itunescon_user: $APPLE_EMAIL
+      - cache-push@2: {}
+    after_run: []
   build:
     steps:
       - activate-ssh-key@4:
@@ -58,57 +106,6 @@ workflows:
             - android_additional_params: >-
                 --release --build-number $GIT_CLONE_COMMIT_COUNT --target-platform
                 android-arm64
-      - cache-push@2: {}
-    after_run: []
-  deploy-ios:
-    steps:
-      - activate-ssh-key@4:
-          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-      - git-clone@4: {}
-      - certificate-and-profile-installer@1: {}
-      - script@1:
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
-                # debug log
-                set -x
-
-                bash $BITRISE_SOURCE_DIR/CI/latest.sh dev
-          title: Get latest version
-      - cache-pull@2: {}
-      - script-runner@0:
-          inputs:
-            - file_path: $BITRISE_SOURCE_DIR/CI/prebuild.sh
-          title: Prebuild
-      - flutter-installer@0:
-          inputs:
-            - installation_bundle_url: $FLUTTER_ARCHIVE_URL
-            - version: dev
-      - script@1:
-          inputs:
-            - content: >-
-                #!/usr/bin/env bash
-
-                # fail if any commands fails
-
-                set -e
-
-                # debug log
-
-                set -x
-
-
-                flutter build ios --config-only --no-codesign --release
-                --build-number $GIT_CLONE_COMMIT_COUNT
-          title: flutter build ios
-      - xcode-archive@3: {}
-      - deploy-to-itunesconnect-application-loader@1:
-          inputs:
-            - password: $APPLE_PASSWORD
-            - app_password: $APPLE_2FA
-            - itunescon_user: $APPLE_EMAIL
       - cache-push@2: {}
     after_run: []
 app:
